server.port=${PORT:9090}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

report.upload-dir=uploads/resume
logging.level.org.springframework=WARN
logging.level.root=INFO
logging.level.org.springframework.security=WARN
spring.jmx.enabled=false

resend.api-key=${RESEND_API_KEY}
resend.from-email=${RESEND_FROM_EMAIL}
resend.to-email=${RESEND_TO_EMAIL}
